version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce      
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build docker images
          command: |
            docker version
            docker images
            docker build -t summitmeetjs .
            docker images
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              CLUSTER='cluster-meetjs'
              FAMILY='task-meetjs'
              DOCKER_IMAGE='summitmeetjs'
              TASK='task-meetjs'
              SERVICE='service-meetjs'
              # Login to AWS
              aws configure set region $AWS_REGION
              $(aws ecr get-login)
              # Tag and push docker image
              docker tag summitmeetjs $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:latest
              docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:latest
              # Create task for docker deploy
              task_template='[
                {
                  "volumesFrom": [],
                  "memory": 300,
                  "portMappings": [
                    {
                      "hostPort": 80,
                      "containerPort": 80,
                      "protocol": "tcp"
                    }
                  ],
                  "essential": true,
                  "entryPoint": [],
                  "mountPoints": [],
                  "name": "container-meetjs",
                  "environment": [],
                  "links": [],
                  "image": "861611597471.dkr.ecr.eu-central-1.amazonaws.com/summitmeetjs:latest",
                  "cpu": 10
                }
              ]'
              echo "$task_template"

              task_def=$(printf "$task_template" $TASK $AWS_ACCOUNT_ID $TASK latest)

              # Register task definition
              json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")

              # Grab revision # using regular bash and grep
              revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')

              # Deploy revision
              aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
              return 0
            fi
